name: tymoff
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  transformer_page_view:

  #Old
  dio: ^3.0.7


  #Latest
  http: ^0.12.0+2
  build_runner: ^1.6.6

  thumbnails: ^1.0.1
  path_provider: ^1.4.0
  countdown: ^0.1.0

  shared_preferences: ^0.5.3+4
  rxdart: ^0.22.4
  percent_indicator: ^2.1.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^0.1.2

  video_player: ^0.10.2+5
  url_launcher: ^5.2.5

  webview_flutter: ^0.3.15+1
  flutter_offline: ^0.2.4+1
  uuid: ^2.0.2
  event_bus: ^1.1.0

  flutter_local_notifications: ^0.8.4+3

  flutter_crashlytics: ^1.0.0
  firebase_crashlytics: ^0.1.0+3
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^5.1.6
  firebase_dynamic_links: ^0.5.0+7

  format_bytes: ^1.0.1
  flutter_downloader: ^1.3.3
  numberpicker: ^1.1.0
  flutter_html: ^0.11.0
  cached_network_image: ^2.0.0-rc

  shimmer: ^1.0.1
  fluttertoast: ^3.1.3

    #flutter_webview_plugin:
   # git:
    #  url: git://github.com/fluttercommunity/flutter_webview_plugin

  #firebase_auth: ^0.11.0
  #cloud_firestore: ^0.11.0+1
  # image_picker:
  # camera: ^0.2.6

  #Need to Update Library - Munish

  json_serializable: ^3.2.3
  flutter_staggered_grid_view: ^0.3.0
  #share: ^0.6.3+1
  flutter_svg: ^0.14.3
  zefyr: ^0.8.0
  image_picker: ^0.6.1+10
  #gif_ani: ^0.0.2
  permission_handler: ^3.3.0
  appsflyer_sdk: ^1.2.0
  dotted_border: ^1.0.3
  screen: ^0.0.5
  flutter_udid: ^1.0.1
  photo_view: ^0.8.2
  esys_flutter_share: ^1.0.2
  encrypt: ^3.3.1
  scroll_to_index: ^1.0.2
  image_cropper: ^1.1.0
  youtube_player_flutter: ^6.0.3+2
  #sms_receiver: ^0.2.0
  sms_autofill: ^1.1.1
  app_settings: 2.0.2
  notification_permissions: ^0.4.3
  open_file: ^2.1.1

  flutter_uploader: ^1.2.0
  progress_indicators: ^0.1.4
  badges: ^1.1.0
  file_picker: ^1.4.3+2
  video_thumbnail: ^0.1.7
  photofilters: ^1.0.5
  flutter_image_editor: ^1.2.0
  filesize: ^1.0.4

  #qrscan: ^0.2.17
  qr_code_scanner: ^0.0.12

dev_dependencies:
  flutter_picker: ^1.1.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Acme
      fonts:
        - asset: fonts/acme_regular.ttf

    - family: Arapey
      fonts:
        - asset: fonts/arapey_regular.ttf
        - asset: fonts/arapey_regularItalic.ttf

    - family: CormorantGaramond
      fonts:
        - asset: fonts/cormorantgaramond_regular.ttf

    - family: EbGaramond
      fonts:
        - asset: fonts/ebgaramond_regular.ttf

    - family: JosefinSans
      fonts:
        - asset: fonts/josefinsans_regular.ttf

    - family: KaushanScript
      fonts:
        - asset: fonts/kaushanscript_regular.ttf

    - family: LibreBaskerville
      fonts:
        - asset: fonts/librebaskerville_regular.ttf

    - family: Lobster
      fonts:
        - asset: fonts/lobster_regular.ttf

    - family: Lora
      fonts:
        - asset: fonts/lora_regular.ttf

    - family: Lusitana
      fonts:
        - asset: fonts/lusitana_regular.ttf

    - family: NotoSerif
      fonts:
        - asset: fonts/notoserif_regular.ttf

    - family: PTSerif
      fonts:
        - asset: fonts/ptserif_regular.ttf

    - family: Quicksand
      fonts:
        - asset: fonts/quicksand_regular.ttf

    - family: Satisfy
      fonts:
        - asset: fonts/satisfy-regular.ttf

    - family: SawarabiMincho
      fonts:
        - asset: fonts/sawarabimincho_regular.ttf

    - family: SpecialElite
      fonts:
        - asset: fonts/specialelite_regular.ttf

    - family: Vollkorn
      fonts:
        - asset: fonts/vollkorn_regular.ttf
    - family: Helvetica
      fonts:
        - asset: fonts/helvetica_neue.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages